In [68]:
import numpy as np
import pandas as pd
import urllib.request
import os
import shutil

In [63]:
url = 'https://www.datos.gov.co/resource/icwf-97sk.csv '
urllib.request.urlretrieve(url, './data/data.csv')


('./data/data.csv', <http.client.HTTPMessage at 0x1a8ccf25270>)

In [64]:
df_base = pd.read_csv('./data/data.csv')
df = df_base.copy()

In [12]:
df = df[0:5000:1]
df

the_geom  Departamento  \
0     MULTIPOLYGON (((-73.90982066974527 4.502760293...  Cundinamarca   
1     MULTIPOLYGON (((-73.64721722862825 4.803926350...  Cundinamarca   
2     MULTIPOLYGON (((-73.64597867778059 4.671679496...  Cundinamarca   
3     MULTIPOLYGON (((-73.74690154954533 5.105043466...  Cundinamarca   
4     MULTIPOLYGON (((-73.83992833266608 5.174391813...  Cundinamarca   
...                                                 ...           ...   
4995  MULTIPOLYGON (((-73.74004505217653 4.964906367...  Cundinamarca   
4996  MULTIPOLYGON (((-73.72555195502046 4.963726322...  Cundinamarca   
4997  MULTIPOLYGON (((-73.79546837792032 4.969046636...  Cundinamarca   
4998  MULTIPOLYGON (((-73.72595630515397 4.972352823...  Cundinamarca   
4999  MULTIPOLYGON (((-73.71667679038201 4.972615233...  Cundinamarca   

      Código departamento Municipio  Código municipio  Gridcode  \
0                      25    Ubaque             25841         0   
1                      25     Junín             25372         8   
2                      25     Junín             25372         1   
3                      25    Suesca             25772         0   
4                      25     Tausa             25793         0   
...                   ...       ...               ...       ...   
4995                   25  Sesquilé             25736         0   
4996                   25  Sesquilé             25736         0   
4997                   25  Sesquilé             25736         0   
4998                   25  Sesquilé             25736         0   
4999                   25  Sesquilé             25736         0   

              Aptitud  Área (ha)  Consecutivo  
0             No apta     952.39           92  
1     Exclusión legal      27.01          255  
2        Aptitud baja     595.45          393  
3             No apta    1969.11          394  
4             No apta    2063.17          395  
...               ...        ...          ...  
4995          No apta       0.01         4750  
4996          No apta       4.77         4751  
4997          No apta       6.26         4752  
4998          No apta       0.05         4753  
4999          No apta       2.78         4754  

[5000 rows x 9 columns]

In [15]:
df.drop(['Departamento','Código departamento','Código municipio'],axis = 1, inplace=True)

In [16]:
df

the_geom Municipio  Gridcode  \
0     MULTIPOLYGON (((-73.90982066974527 4.502760293...    Ubaque         0   
1     MULTIPOLYGON (((-73.64721722862825 4.803926350...     Junín         8   
2     MULTIPOLYGON (((-73.64597867778059 4.671679496...     Junín         1   
3     MULTIPOLYGON (((-73.74690154954533 5.105043466...    Suesca         0   
4     MULTIPOLYGON (((-73.83992833266608 5.174391813...     Tausa         0   
...                                                 ...       ...       ...   
4995  MULTIPOLYGON (((-73.74004505217653 4.964906367...  Sesquilé         0   
4996  MULTIPOLYGON (((-73.72555195502046 4.963726322...  Sesquilé         0   
4997  MULTIPOLYGON (((-73.79546837792032 4.969046636...  Sesquilé         0   
4998  MULTIPOLYGON (((-73.72595630515397 4.972352823...  Sesquilé         0   
4999  MULTIPOLYGON (((-73.71667679038201 4.972615233...  Sesquilé         0   

              Aptitud  Área (ha)  Consecutivo  
0             No apta     952.39           92  
1     Exclusión legal      27.01          255  
2        Aptitud baja     595.45          393  
3             No apta    1969.11          394  
4             No apta    2063.17          395  
...               ...        ...          ...  
4995          No apta       0.01         4750  
4996          No apta       4.77         4751  
4997          No apta       6.26         4752  
4998          No apta       0.05         4753  
4999          No apta       2.78         4754  

[5000 rows x 6 columns]

In [17]:
df.describe(include=object)

the_geom Municipio  Aptitud
count                                                5000      5000     5000
unique                                               5000       111        5
top     MULTIPOLYGON (((-73.90982066974527 4.502760293...   Fómeque  No apta
freq                                                    1      1099     2476

In [129]:
a = df['the_geom'][:]

In [130]:
%run utils.py

In [131]:
lista = []
for i in a:
    m = trans_mp(i)
    lista.append(m)

In [132]:
lista = np.asarray(lista)#np.array(lista)
lista
# lista.astype(float)

C:\Users\Cristian Durango\AppData\Local\Temp\ipykernel_3312\1199147740.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  lista = np.asarray(lista)#np.array(lista)


array([array([[-73.90982067,   4.50276029],
              [-73.90809065,   4.50221175],
              [-73.90731003,   4.50185309],
              ...,
              [-73.91154828,   4.50318926],
              [-73.9115085 ,   4.50316115],
              [-73.90982067,   4.50276029]]),
       array([[-73.64721723,   4.80392635],
              [-73.64722772,   4.80386989],
              [-73.6472348 ,   4.80382759],
              ...,
              [-73.64718616,   4.80408643],
              [-73.64720115,   4.80400594],
              [-73.64721723,   4.80392635]]),
       array([[-73.64597868,   4.6716795 ],
              [-73.64597918,   4.67085852],
              [-73.6458347 ,   4.67085843],
              ...,
              [-73.62550121,   4.65798371],
              [-73.62550104,   4.65825737],
              [-73.6252242 ,   4.65825719]]), ...,
       array([[-73.79546838,   4.96904664],
              [-73.79555575,   4.96930875],
              [-73.79555575,   4.96959429],
        

In [44]:
listb = [i for i in df['Municipio']]
listc = [i for i in df['Aptitud']]
listd = [i for i in df['Gridcode']]
liste = [i for i in df['Área (ha)']]
listb

['Ubaque',
 'Junín',
 'Junín',
 'Suesca',
 'Tausa',
 'Ubalá',
 'Medina',
 'Medina',
 'Chía',
 'Medina',
 'Medina',
 'Sasaima',
 'Girardot',
 'Cogua',
 'Tausa',
 'Gachetá',
 'Junín',
 'Ubalá',
 'Ubalá',
 'Ubalá',
 'Ubalá',
 'Guasca',
 'Gachetá',
 'Gachetá',
 'Gachetá',
 'Junín',
 'Anapoima',
 'La Mesa',
 'Bojacá',
 'Fómeque',
 'Fómeque',
 'Fómeque',
 'Fómeque',
 'Fómeque',
 'Fómeque',
 'Fómeque',
 'Guayabal de Síquima',
 'Fómeque',
 'Fómeque',
 'La Vega',
 'Villeta',
 'Subachoque',
 'Subachoque',
 'Supatá',
 'Guatavita',
 'Guatavita',
 'Guatavita',
 'San Francisco',
 'Supatá',
 'Sesquilé',
 'Nemocón',
 'Suesca',
 'Chocontá',
 'Machetá',
 'Chocontá',
 'Villapinzón',
 'Gutiérrez',
 'Fúquene',
 'Fúquene',
 'Susa',
 'Susa',
 'Simijaca',
 'San Bernardo',
 'Fosca',
 'Gutiérrez',
 'Ricaurte',
 'Gutiérrez',
 'Silvania',
 'Apulo',
 'Gachetá',
 'Cachipay',
 'Zipacón',
 'Zipacón',
 'La Calera',
 'La Calera',
 'Madrid',
 'Bogotá, D. C.',
 'Choachí',
 'Sopó',
 'Madrid',
 'Facatativá',
 'Sopó',
 'Fos

In [48]:
new_geo = open('./new_data/the_geo.csv','w')

for i in range(0,len(lista)):
    a = lista[i]
    
    new_geo.write(f'{a} \n')

In [49]:
new_data = open('./new_data/new_data.csv','w')
for i in range(0,len(lista)):   
    a = lista[i]
    b = listb[i]
    c = listc[i]
    d = listd[i]
    e = liste[i]
    
    new_data.write(f'{a},{b},{c},{d},{e} \n')

In [ ]:
shutil.rmtree('./data')